repositories:
- name: bitnami
  url: registry-1.docker.io/bitnamicharts
  oci: true

releases:
  - name: redis
    installed: {{ eq .Environment.Name "dev" | toYaml }}
    namespace: {{ .Namespace }}
    chart: bitnami/redis
    version: 18.19.2
    values:
      - auth:
          password: pass
        architecture: standalone
        image:
          repository: bitnamilegacy/redis

  - name: extra
    installed: {{ ne .Environment.Name "dev" | toYaml }}
    namespace: {{ .Namespace }}
    chart: ./extra
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

  - name: oidc2fer
    version: {{ .Values.version }}
    namespace: {{ .Namespace }}
    chart: ./oidc2fer
    values:
      - env.d/{{ .Environment.Name }}/values.oidc2fer.yaml.gotmpl
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

environments:
  dev:
    values:
      - version: 0.0.1
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml
  staging:
    values:
      - version: 0.0.1
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml
  outscale-production:
    values:
      - version: 0.0.1
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

