attributes:
  givenname:
    openid:
      - given_name
    saml:
      - firstName
      - givenName
  mail:
    openid:
      - email
    saml:
      - email
      - emailAddress
      - mail
  usual_name:
    openid:
      - usual_name
    saml:
      - sn
      - surname
      - lastName
  acr:
    openid:
      - acr
  eduPersonPrincipalName:
    saml:
      - eduPersonPrincipalName
  eduPersonAffiliation:
    saml:
      - eduPersonAffiliation
  uid:
    openid:
      - uid
